### ISSUE TITLE
Return raw output of pastebin links when requested

### ISSUE THREAD

**Issue by jkcclemens** [jkcclemens/bins#11]
```
[16:04:59]  <+Zarthus>	your bins thing to have raw fetching
[16:05:52]  <+Zarthus>	yeah but i'm requesting it to detect with bins --in https://gist.github.com/dork/somedorkgist to return the raw content
```

**Comment by Zarthus** [comment]
Originally request:
```
2016-06-09 11:50:24     +Zarthus        yo jkcclemens, bins actually looks pretty neat
2016-06-09 11:50:51     +Zarthus        but can it read content from a pastebin site as well?
2016-06-09 11:51:41     +Zarthus        for example `xclip -sel clip <(bins --in https://gist.github.com/zarthus/$hex)` # Automatically fetch raw content without HTML
```

**Comment by jkcclemens** [comment]
Gists can have multiple files. I'm thinking that it would be necessary to do something like 
```
bins --in <gist url> <file name>
```
for gist and just
```
bins --in <url>
```
for other bins. Of course, if the gist only has one file, the name would be optional.

Thoughts?

**Comment by Zarthus** [comment]
Exactly that sounds reasonable to me.

Later down the line it may be an idea to consider some optional switches.
Some ideas: 

`--as-one-file` (separate files with `--- file.rb ---`)

`--first-file` (get the first file only, alphabetically sorted)

`--raw-urls` (this works for all of them. - Convert the normal URL into a raw URL so you can manually curl); for gist this would just return multiple urls which you can then `head -1` and cURL yourself.

**Comment by jkcclemens** [comment]
I'm also thinking of having indexed pastes support the file syntax, so even a hastebin, pastebin, etc. multi-file paste could support getting one file from an index. If no file is given, it will just give the raw output of the index.

**Comment by jkcclemens** [comment]
While e6f145f implements this issue in a basic manner, it does not fully implement all features, so the issue is remaining open.

**Comment by jkcclemens** [comment]
- [ ] `--nth`/`-n` – get file by index
- [ ] `--all`/`-a` – get all files (separated by `\n\n--- FILE NAME ---\n\n`)
- [ ] `--urls`/`-u` – get urls only (works with -n)
- [ ] `--raw-urls`/`-r` – get raw urls only (works with -n)

**Comment by jkcclemens** [comment]
`--all` has a short flag as `-L`, but otherwise implemented. Finally closing.
