### ISSUE TITLE
Support line numbering (and marking for services like GitHub) with an option in input mode.

### ISSUE THREAD

**Issue by Zarthus** [jkcclemens/bins#20]
Something simple like the linux tool `nl` but then natively within bins.  Can pick up on separate files for services like GitHub Gist.

Bonus points if GitHub Gist line markings are able to be coloured or marked differently

**Comment by jkcclemens** [comment]
Uncertain if I want to implement this or use `nl` and awesome piping instead.

**Comment by jkcclemens** [comment]
Just as a note, syntax coloring can easily be done with a simple pipe using [pygments](http://pygments.org/docs/cmdline/).
