### ISSUE TITLE
Write the multiple files to the CWD

### ISSUE THREAD

**Issue by lol768** [jkcclemens/bins#25]
Earlier, in an IRC channel on an IRC network:

```
<@jkcclemens> no, it can't write them to all separate files
```

But _can it_, in a future version?

**Comment by jkcclemens** [comment]
Proposed `-w`/`--write` mode. Not sure if `-wi` or if `-w` would conflict with `-i`.

- [ ] `-w`/`--write` mode
  - [ ] naming conflicts (`_#` before extension)

**Comment by lol768** [comment]
Problem: Filenames available on some platforms but not on others? (Thinking windows)

**Comment by jkcclemens** [comment]
I haven't done any work with it, but I think I can handle this by coercing `String` into `OsString`, which provides platform-specific strings. If I do a lossy coercion, I should always be able to write the file.

**Comment by lol768** [comment]
Thanks!
