### ISSUE TITLE
Strange error message when hastebin returns an improper response.

### ISSUE THREAD

**Issue by AKPWebDesign** [jkcclemens/bins#30]
When a hastebin (and possibly others?) is configured to have a maximum paste size, and bins attempts to upload a file greater than that size, the following error is displayed:

```
json decoder error
MissingFieldError("key")
```

It might be a good idea to verify the response from the bin service and output an appropriate error if needed.

**Comment by AKPWebDesign** [comment]
@jkcclemens asked to see what response the hastebin server sends when attempting to create a document that is too large, so I ran `curl -X POST --data "@/path/to/file" https://hastebin.com/documents`, specifying a 33 MB file, and got the following response from the server:

```json
{"message":"Document exceeds maximum length."}
```

**Comment by AKPWebDesign** [comment]
Of course, now that I'm testing this in bins, I'm getting a `status code 400 Bad Request` error message, rather than the `json decoder error` I was getting before.

**Comment by jkcclemens** [comment]
2.0.0 behavior
`[04:30:21] ERROR – error uploading to hastebin: the bin responded with the following error: Document exceeds maximum length.`
