### ISSUE TITLE
Support for transfer.sh

### ISSUE THREAD

**Issue by AKPWebDesign** [jkcclemens/bins#44]
What do you think about adding support for [transfer.sh](https://transfer.sh/)? Seems easy enough, it's basically the same as sprunge.

**Comment by jkcclemens** [comment]
I'm not sure about adding support for file sharing sites as pastebins. transfer.sh might let you view text files as plain, but others definitely do not. I don't really view transfer.sh as a pastebin.

**Comment by AKPWebDesign** [comment]
That's a fair point. Now that you bring that difference up, I agree.
