### ISSUE TITLE
Not working with Rust stable channel :) Any chance for it?

### ISSUE THREAD

**Issue by dmilith** [jkcclemens/bins#9]

**Comment by jkcclemens** [comment]
```
% rustc --version
rustc 1.9.0 (e4e8b6668 2016-05-18)
```

1.9.0 is the current stable release, and it compiles fine for me. What version are you on?

**Comment by dmilith** [comment]
Ok, I''m using 1.7 now. My bad. Will update then.

**Comment by jkcclemens** [comment]
No problem. :) If you're still having issues on 1.9.0, reopen this and we'll get it sorted out.

**Comment by dmilith** [comment]
Builds just fine :) great, thanks! You can just put info that Rust 1.7 isn't enough to compile this project :)
